### ISSUE TITLE
I just have fewer pedigree. I'm afraid i could not get better results!

### ISSUE THREAD

**Issue by zhangshouwei-yizhi** [statgenetics/rvnpl#4]
Dear Author:
        Recently i used rvnpl to analysis multiple-pedigree data. Now I use gnomAD_EAS to evaluate minor allele frequecy. Because some sites can not be annotated, i assign a value equal to 0 to further analysis. Do you think whether it's reasonable or not?
       In my research, i have four sets of data, the first  have 10 pedigree, the second have 4, the third have 5 pedigree, the fourth  include the first, the second and the third. For them, i run this programme respectively. Because my pedigree are so fewer, i'm afraid i could not get better results, do you have any suggestions?
Phillip
Best wishes for you!

**Comment by gaow** [comment]
Hi @zhangshouwei309194, 

>  Because some sites can not be annotated, i assign a value equal to 0 to further analysis.

If you set those MAF to zero you essentially exclude them from the analysis. I'm not sure if it is the best thing to do. @percylinhai what did you do in your data analysis when a variant cannot be found in gnomAD? I think it is perhaps better to replace it with "singleton frequency" in gnomAD --  i.e., 1 / (2 * sample size of the gnomAD reference population)? 

>  the first have 10 pedigree, the second have 4, the third have 5 pedigree, the fourth include the first, the second and the third. 

It sounds like it should be good enough to just run the analysis on the 4th data-set? 

What issue did you have with this original message you sent:

```
Process EncoderWorker-17: complied_data.append(data[person][marker[famid]]) KeyError:
```
did you do something and fixed it? If so I'd very much like to know what it is so we can improve our error prompt. Thanks a lot!

**Comment by zhangshouwei-yizhi** [comment]
`Process EncoderWorker-17: complied_data.append(data[person][marker[famid]]) KeyError:`
About this error,  when my data set include SNP and Indel, this error has occured, but after removing InDel, it works well and no exception has occured. Thanks for your help!

**Comment by zhangshouwei-yizhi** [comment]
**"If you set those MAF to zero you essentially exclude them from the analysis."**    
You means that when i set those MAF to 0,  those site will be ignorted. But i remember when i set ”--freq gnomAD_EAS -c 0.01“ , it will filter those site that have MAF > 0.01. Below this threshold, it will be kept.
According to your suggestions, "singleton frequency" in gnomAD -- i.e., 1 / (2 * sample size of the gnomAD reference population)", i will set those values as mentioned above.

**Comment by gaow** [comment]
@percylinhai will we remove variants having reference MAF = 0?

**Comment by gaow** [comment]
@percylinhai what did you do in your data analysis when a variant cannot be found in gnomAD? Do we remove it, or replace with singletons MAF as I ?
